<a href="https://colab.research.google.com/github/breno-xp/Curso-Pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

# Chapter 0 - Fundamentals

## Introduction

In [ ]:
test_essentialS = torch.tensor([1, 2, 3], [])
# The firt array is the matrix, there should be only 1

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
matrix_err = torch.tensor([[[1, 2, 3],
                          [4, 5]]])
# The arrays must have the same number os elements

ValueError: expected sequence of length 3 at dim 2 (got 2)

In [ ]:
test_1 = torch.tensor([1, 2, 3])

test_1.shape
# Inside the matrix (dim = 0) there is 3 items

torch.Size([3])

In [ ]:
test_1.ndim

1

In [ ]:
test_2 = torch.tensor([[1, 2], [2, 3], [3, 4]])

test_2.shape
# Inside the dim = 0 there is 3 arrays, inside those (dim = 1) there are 2 items

torch.Size([3, 2])

In [ ]:
test_2.ndim

2

In [ ]:
test_3 = torch.tensor([[[], []] , [[], []], [[], []]])

test_3.shape
# Inside the dim = 0 there is 3 arrays, inside those (dim = 1) there are 2 arrays (dim = 2), each with 0 items

torch.Size([3, 2, 0])

In [ ]:
test_3.ndim

3

In [ ]:
test_4 = torch.tensor([[[1], [1]] , [[1], [1]], [[1], [1]]])

test_4.shape
# Inside the dim = 0 there is 3 arrays (dim = 1), inside those there are 2 arrays (dim = 2), each with 1 item

torch.Size([3, 2, 1])

In [ ]:
test_4.ndim

3

In [ ]:
test_5 = torch.tensor([[[[[[]]]]]])
test_5.ndim

6

In [ ]:
test_5.shape

torch.Size([1, 1, 1, 1, 1, 0])

In [ ]:
scalar = torch.tensor(1)
# A scalar has a single value | Lowercase
scalar.item()

1

In [ ]:
scalar = torch.tensor(1, 2, 3)

TypeError: tensor() takes 1 positional argument but 3 were given

In [ ]:
test_5.item()

RuntimeError: a Tensor with 0 elements cannot be converted to Scalar

In [ ]:
vector = torch.tensor([1, 2, 3])
# 1 dimension | Lowercase

In [ ]:
MATRIX = torch.tensor([[1, 2 ,3],
                       [4, 5, 6],
                       [7, 8, 9]])
# 2 dimensions | Uppercase

In [ ]:
TENSOR = torch.tensor([[[1], [2]],
                       [[3], [4]],
                       [[5], [6]]])
# 3 ~ n  dimensions | Uppercase

## Random tensors

In [ ]:
 random_tensor = torch.rand(2, 3, 2, 3)

In [ ]:
random_tensor

tensor([[[[0.6103, 0.8248, 0.9316],
          [0.8466, 0.8497, 0.6099]],

         [[0.1417, 0.0412, 0.5058],
          [0.7883, 0.8350, 0.3969]],

         [[0.2123, 0.9345, 0.8485],
          [0.6994, 0.4530, 0.2059]]],


        [[[0.9733, 0.3555, 0.5157],
          [0.6591, 0.4436, 0.0888]],

         [[0.1373, 0.1783, 0.2724],
          [0.7330, 0.3688, 0.7512]],

         [[0.0682, 0.2601, 0.9580],
          [0.8144, 0.4415, 0.0993]]]])

In [ ]:
random_tensor.ndim

4

In [ ]:
random_tensor.shape

torch.Size([2, 3, 2, 3])

In [ ]:
 random_image_size_tensor = torch.rand(size=(224, 224, 3)) # size is not necessary really
 random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Range of tensors

In [ ]:
digits = torch.arange(0, 10)
digits

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pairs = torch.arange(start=0, end=101, step=2) # Again, the variables are not necessary
pairs

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
digits_zeros = torch.zeros_like(input=digits)
digits_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Datatypes

In [ ]:
data = torch.tensor([1.0, 3.0, 5.0], dtype = None, #float32 (default) or float16
                                     device = None, #cpu, cuda
                                     requires_grad = False) #track gradients
data.dtype

torch.float32

### Getting information from tensor (attributes)
1. Not right datatype - `tensor.dtype`
2. || shape - `tensor.shape`
3. || device - `tensor.device`

In [ ]:
eg_tensor = torch.rand(3, 4)
eg_tensor.dtype, eg_tensor.shape, eg_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

* Changing the type value

In [ ]:
eg_tensor.type(torch.float16)

TypeError: 'torch.device' object is not callable

## Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor - 100

tensor([-99, -98, -97])

In [ ]:
tensor * 100

tensor([100, 200, 300])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[7, 8, 9], [10, 11, 12]])
tensor_c = torch.tensor([[7, 8], [9, 10], [11, 12]])

tensor_a * tensor_b #Element wise product

tensor([[ 7, 16, 27],
        [40, 55, 72]])

In [ ]:
%%time
torch.matmul(tensor_a, tensor_c) #Multiplying with matrix

CPU times: user 597 µs, sys: 0 ns, total: 597 µs
Wall time: 387 µs


tensor([[ 58,  64],
        [139, 154]])

### For the matrixes multiplication to work the number of inner values must be equal
* `(2, 3) @ (3, 2) Will work`
* `(2, 3) @ (2, 3) Will not work`

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.0792, 0.0481],
        [0.3452, 0.2453]])

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

* To fix a shape issue use **transpose** (**T**) attribute, which shifts the axes or dimensions of a given tensor

In [ ]:
tensor_a, tensor_b

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [ ]:
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
tensor_b.T

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 50,  68],
        [122, 167]])

In [ ]:
tensor_b, tensor_b.T

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
tensor_b.shape, tensor_b.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

## Finding min, max, mean (average), sum, etc

In [ ]:
x = torch.arange(5, 110, 10)
x, x.dtype

(tensor([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105]), torch.int64)

In [ ]:
x.min(), torch.min(x)

(tensor(5), tensor(5))

In [ ]:
x.max(), torch.max(x)

(tensor(105), tensor(105))

* The mean method requires a floating point type of data

In [ ]:
x.type(torch.float32).mean()

tensor(55.)

In [ ]:
x.sum(), torch.sum(x)

(tensor(605), tensor(605))

* Finds the value

In [ ]:
# Find the position of the minimum value in tensor
x.argmin()

tensor(0)

In [ ]:
# Uses the position found by the argmin method to get the minimum value
x[0]

tensor(5)

In [ ]:
# Find the position of the greatest value in tensor
x.argmax()

tensor(10)

In [ ]:
x[x.argmax()]

tensor(105)

## Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping:** reshapes an input tensor to a defined shape
* **View:** does the same thing as reshaping but shares the same memory as the original when attributed to another variable
* **Stacking:** - combines tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze:** removes all `1` dimensions from a tensor
* **Unsqueeze:** add a `1` dimension to a target tensor
* **Permute:** Return a view fo the input with dimensions permuted (swapped) in a certain way

In [ ]:
a = torch.rand(2, 2, 3)
a

tensor([[[0.0677, 0.8971, 0.1116],
         [0.4244, 0.8455, 0.9726]],

        [[0.4584, 0.4286, 0.4805],
         [0.9080, 0.0055, 0.5969]]])

* To reshape take into account the number of elements must be equal, meaning the product must match the number of elements

In [ ]:
a_reshaped = a.reshape(12)
a_reshaped

tensor([0.0677, 0.8971, 0.1116, 0.4244, 0.8455, 0.9726, 0.4584, 0.4286, 0.4805,
        0.9080, 0.0055, 0.5969])

In [ ]:
a_reshaped = a_reshaped.reshape(4, 3)
a_reshaped

tensor([[0.0677, 0.8971, 0.1116],
        [0.4244, 0.8455, 0.9726],
        [0.4584, 0.4286, 0.4805],
        [0.9080, 0.0055, 0.5969]])

In [ ]:
b_view_a = a.view(2, 6)
b_view_a

tensor([[0.0677, 0.8971, 0.1116, 0.4244, 0.8455, 0.9726],
        [0.4584, 0.4286, 0.4805, 0.9080, 0.0055, 0.5969]])

In [ ]:
b_view_a[0][0] = 0.6677

In [ ]:
a, b_view_a

(tensor([[[0.6677, 0.8971, 0.1116],
          [0.4244, 0.8455, 0.9726]],
 
         [[0.4584, 0.4286, 0.4805],
          [0.9080, 0.0055, 0.5969]]]),
 tensor([[0.6677, 0.8971, 0.1116, 0.4244, 0.8455, 0.9726],
         [0.4584, 0.4286, 0.4805, 0.9080, 0.0055, 0.5969]]))

* Stack começa aqui

In [ ]:
stack = torch.rand(3, 3)
stack, stack.ndim

(tensor([[0.0634, 0.4970, 0.0606],
         [0.1255, 0.0473, 0.8085],
         [0.1094, 0.9606, 0.3250]]),
 2)

In [ ]:
 # When the dim value = 0, just concatenate
 # dim = 1, look at the first item in dim 1 and unite all, the seconds, thirds and so on
 # dim > 1 keeps the same logic, from the x dimension find the 1st item and unite with others from the same dimension

 inside the stack is equal to the ndim of the tensor,

stack_ed = torch.stack([stack, stack, stack], dim=0) # dim=0 is the default, not necessary to declare
stack_ed

tensor([[[0.6700, 0.8259, 0.2922],
         [0.4596, 0.5267, 0.8191],
         [0.6459, 0.9546, 0.6999]],

        [[0.6700, 0.8259, 0.2922],
         [0.4596, 0.5267, 0.8191],
         [0.6459, 0.9546, 0.6999]],

        [[0.6700, 0.8259, 0.2922],
         [0.4596, 0.5267, 0.8191],
         [0.6459, 0.9546, 0.6999]]])

In [ ]:
stack_ed = torch.stack([stack, stack, stack], dim=1)
stack_ed

tensor([[[0.6700, 0.8259, 0.2922],
         [0.6700, 0.8259, 0.2922],
         [0.6700, 0.8259, 0.2922]],

        [[0.4596, 0.5267, 0.8191],
         [0.4596, 0.5267, 0.8191],
         [0.4596, 0.5267, 0.8191]],

        [[0.6459, 0.9546, 0.6999],
         [0.6459, 0.9546, 0.6999],
         [0.6459, 0.9546, 0.6999]]])

In [ ]:
stack_ed = torch.stack([stack, stack, stack], dim=2)
stack_ed

tensor([[[0.6700, 0.6700, 0.6700],
         [0.8259, 0.8259, 0.8259],
         [0.2922, 0.2922, 0.2922]],

        [[0.4596, 0.4596, 0.4596],
         [0.5267, 0.5267, 0.5267],
         [0.8191, 0.8191, 0.8191]],

        [[0.6459, 0.6459, 0.6459],
         [0.9546, 0.9546, 0.9546],
         [0.6999, 0.6999, 0.6999]]])

In [ ]:
# This error occurs because ndim is 2

stack_ed = torch.stack([stack, stack, stack], dim=3)
stack_ed

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [ ]:
stack_3 = torch.rand(2, 2, 3)
stack_3

tensor([[[0.0022, 0.1982, 0.5851],
         [0.0717, 0.0301, 0.2743]],

        [[0.1360, 0.0014, 0.6417],
         [0.9254, 0.5931, 0.7832]]])

In [ ]:
stack_ed = torch.stack([stack_3, stack_3, stack_3], dim=0)
stack_ed

tensor([[[[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]],

         [[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]]],


        [[[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]],

         [[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]]],


        [[[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]],

         [[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]]]])

In [ ]:
stack_ed = torch.stack([stack_3, stack_3, stack_3], dim=1)
stack_ed

tensor([[[[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]],

         [[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]],

         [[0.0022, 0.1982, 0.5851],
          [0.0717, 0.0301, 0.2743]]],


        [[[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]],

         [[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]],

         [[0.1360, 0.0014, 0.6417],
          [0.9254, 0.5931, 0.7832]]]])

In [ ]:
stack_ed = torch.stack([stack_3, stack_3, stack_3], dim=2)
stack_ed

tensor([[[[0.0022, 0.1982, 0.5851],
          [0.0022, 0.1982, 0.5851],
          [0.0022, 0.1982, 0.5851]],

         [[0.0717, 0.0301, 0.2743],
          [0.0717, 0.0301, 0.2743],
          [0.0717, 0.0301, 0.2743]]],


        [[[0.1360, 0.0014, 0.6417],
          [0.1360, 0.0014, 0.6417],
          [0.1360, 0.0014, 0.6417]],

         [[0.9254, 0.5931, 0.7832],
          [0.9254, 0.5931, 0.7832],
          [0.9254, 0.5931, 0.7832]]]])

* **Sequeeze and torch.unsqueeze:** Removes/adds extra brackets, if they exist

In [ ]:
stack = torch.tensor([[[1,2,3], [4,5,6]]])

In [ ]:
stack, stack.shape, stack.squeeze(0), stack.squeeze(0).shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [ ]:
stack.squeeze(1), stack.squeeze(1).shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([1, 2, 3]))

In [ ]:
stack = torch.tensor([[[[1,2,3]], [[4,5,6]]]])

In [ ]:
stack, stack.shape

(tensor([[[[1, 2, 3]],
 
          [[4, 5, 6]]]]),
 torch.Size([1, 2, 1, 3]))

In [ ]:
stack.squeeze(0)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [ ]:
stack.squeeze(2)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
stack.squeeze(0, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
stack, stack.unsqueeze(3)

(tensor([[[[1, 2, 3]],
 
          [[4, 5, 6]]]]),
 tensor([[[[[1, 2, 3]]],
 
 
          [[[4, 5, 6]]]]]))

In [ ]:
vector = torch.arange(0, 11)
vector

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
vector.unsqueeze(0)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
# Quando a dimenção a add um [] é igual ndim + 1 os elementos serão circundados
vector.unsqueeze(1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [ ]:
stack

tensor([[[[1, 2, 3]],

         [[4, 5, 6]]]])

In [ ]:
stack.shape

torch.Size([1, 2, 1, 3])

In [ ]:
stack = stack.squeeze(0, 2)

In [ ]:
stack.shape

torch.Size([2, 3])

In [ ]:
stack

tensor([[1, 2, 3],
        [4, 5, 6]])

* **Permute:** Organizes the dimensions in a specified order, reshaping as necessary

**PS:** Just like view, shares the same memory

In [ ]:
stack.permute(1, 0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
vector

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
stack[0, 2]

tensor(3)

In [ ]:
stack

tensor([[1, 2, 3],
        [4, 5, 6]])

## Indexing

In [ ]:
ex = torch.rand(2, 3, 3)
ex

tensor([[[0.4404, 0.9886, 0.3519],
         [0.4858, 0.5944, 0.6667],
         [0.4999, 0.6791, 0.8760]],

        [[0.4601, 0.0480, 0.3962],
         [0.1305, 0.3701, 0.5218],
         [0.6647, 0.9474, 0.9817]]])

In [ ]:
ex[0]

tensor([[0.4404, 0.9886, 0.3519],
        [0.4858, 0.5944, 0.6667],
        [0.4999, 0.6791, 0.8760]])

In [ ]:
# Like JS, but with other option
ex[0][0], ex[0, 0]

(tensor([0.4404, 0.9886, 0.3519]), tensor([0.4404, 0.9886, 0.3519]))

In [ ]:
ex[0][0][0]

tensor(0.4404)

In [ ]:
# : means to get from all arrays of that dim
## in this case, get from all arrays in dim0 the second array's second item
ex[:, 1, 1]

tensor([0.5944, 0.3701])

In [ ]:
ex[:, 2, :]

tensor([[0.4999, 0.6791, 0.8760],
        [0.6647, 0.9474, 0.9817]])

## PyTorch & NumPy

PyTorch requires NumPy, which is a library with multiple calculation functions

* Take data from NumPy and convert to PyTorch tensor

In [ ]:
array = np.arange(1, 11)
array, array.dtype

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), dtype('int64'))

In [ ]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

* Take into account the fact that the default value in NumPy is `dtype = float64` or `int64`, and in torch `dtype = float32`

* To convert the `dtype` to float32 do as follows:

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.float32)

* Take data from PyTorch to NumPy:

In [ ]:
tensor = torch.zeros(10)
tensor, tensor.dtype

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), torch.float32)

In [ ]:
numpy = tensor.numpy()
numpy, numpy.dtype

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 dtype('float32'))

 ## Reproducibility (Making random tensors less random)

 Neural networks learn taking random tensors, making operations to find patterns and then update the random numbers multiple times until the calculations output a good representation of the expected data output

 To reduce randomness we use the **random seed**

In [ ]:
tensor_a = torch.rand(3, 4)
tensor_b = torch.rand(3, 4)
tensor_a, tensor_b

(tensor([[0.3158, 0.1765, 0.2927, 0.9295],
         [0.9146, 0.2854, 0.0241, 0.2317],
         [0.1923, 0.2486, 0.6258, 0.8003]]),
 tensor([[0.6411, 0.2076, 0.4698, 0.9483],
         [0.5360, 0.9798, 0.1262, 0.7378],
         [0.9106, 0.1149, 0.0714, 0.9252]]))

In [ ]:
tensor_a == tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

* Random but reproducible tensors

In [ ]:
RANDOM_SEED = 3

* In notebook it is necessary to set the seed before the tensor creation

In [ ]:
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(3, 4)
tensor_c, tensor_d, tensor_c == tensor_d

(tensor([[0.0043, 0.1056, 0.2858, 0.0270],
         [0.4716, 0.0601, 0.7719, 0.7437],
         [0.5944, 0.8879, 0.4510, 0.7995]]),
 tensor([[0.0043, 0.1056, 0.2858, 0.0270],
         [0.4716, 0.0601, 0.7719, 0.7437],
         [0.5944, 0.8879, 0.4510, 0.7995]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## Running tensors and PyToch on GPU's (for faster computation)

In [ ]:
!nvidia-smi

Mon May  5 19:22:40 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

* Check access to GPU with PyTorch

In [ ]:
torch.cuda.is_available()

True

* Setup device agnostic code (use gpu if available)



In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### Putting tensors (and models) on the GPU

In [ ]:
tensor_cpu = torch.tensor([1, 2, 3])
tensor_cpu, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
device

'cuda'

In [ ]:
tensor_gpu = tensor_cpu.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

### Putting tensor (and models) on the CPU (Cause of NumPy)

In [ ]:
tensor_cpu = tensor_gpu.to("cpu")
tensor_cpu, tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
numpy = tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
numpy = tensor_cpu.numpy()

# Chapter 1 - Workflow